### ISSUE TITLE
MSKLC link dead

### ISSUE THREAD

**Issue by miloush** [MicrosoftDocs/globalization#129]
The MSKLC link at https://docs.microsoft.com/en-us/globalization/downloads is not working.

Consider fixing the 82315 and 17223 fwlinks and/or linking directly to
http://www.microsoft.com/en-us/download/details.aspx?id=22339. 

(The latter fwlink is from https://support.microsoft.com/en-us/help/823010/the-microsoft-keyboard-layout-creator which is linked from the bottom of https://docs.microsoft.com/en-us/globalization/windows-keyboard-layouts.)

**Comment by jowilco** [comment]
Hello @miloush. I apologize that we have taken so long to respond to you. The site is in the process of changing ownership and unfortunately it has taken us longer than usual to respond.

I believe that this issue has already been addressed. The links to the Keyboard Layout Creator and the Multilingual App Toolkit both now go to valid locations.

Please can you confirm and close this issue if you agree?

**Comment by jmfrank63** [comment]
@jowilco Is there an ETA? The msklc is an actual jewel and it is dearly missed.

**Comment by jowilco** [comment]
Hi @jmfrank63. Thanks for bringing this to my attention again. I believe that the issue that miloush was seeing and what is happening now are two separate issues. Previously, the link wasn't working, but now the MSKLC is no longer available for download. I'll try to find out who owns this and I'll keep this thread updated.

**Comment by miloush** [comment]
@jowilco sorry for missing your notice, I guess given the link is now not working again I will keep it open.

**Comment by jowilco** [comment]
Hi @jmfrank63, @miloush - the issue with the MSKLC download is an expired signature. Might it be possible to send you the executable directly if you need it during the time that the team is working on getting the updated signature?

**Comment by miloush** [comment]
@jowilco that's good news to me. I'm good, I have the installer. Thank you for the offer!

**Comment by PaulGor** [comment]
The link that works:  https://microsoft-keyboard-layout-creator.software.informer.com/1.4/  
(and click there on "Trusted Download 10.1Mb")

This link should replace non-working link at the bottom of these 2 pages:
https://docs.microsoft.com/en-us/globalization/windows-keyboard-layouts or the same at
https://github.com/MicrosoftDocs/globalization/blob/live/globalization/windows-keyboard-layouts.md

**Comment by miloush** [comment]
If someone wants to find a 3rd party download that Microsoft doesn't consider safe enough to host, that's up to them, but it shouldn't be linked from the documentation as an official source.

**Comment by PaulGor** [comment]
@miloush My bad - I did not look carefully at the link and assumed that it was from microsoft.com

**Comment by jowilco** [comment]
Hi @PaulGor - Thank you for trying to help. I apologize that is taking longer than expected, but we are working on getting the download re-signed and it should be available soon.

**Comment by nschonni** [comment]
When the upload get's fixed, the redirect should probably get updated here too https://github.com/MicrosoftDocs/globalization/blob/master/.openpublishing.redirection.json#L5

**Comment by jowilco** [comment]
@PaulGor @miloush @jmfrank63 The MSKLC is live again. You can access it directly at https://www.microsoft.com/en-us/download/details.aspx?id=102134 and the links within https://docs.microsoft.com/en-us/globalization have been updated.
@nschonni Thank you for catching the redirect - I have updated that too.

I apologize for the delay, and thank you again for bringing it to our attention that MSKLC was no longer available.
