### ISSUE TITLE
3 broken links on Globalization Documentation main page - https://github.com/MicrosoftDocs/globalization/blob/live/globalization/index.md

### ISSUE THREAD

**Issue by alfredoalmeida** [MicrosoftDocs/globalization#131]
This page has 3 broken links:

**1. Getting Started with Globalization**
https://github.com/MicrosoftDocs/globalization/blob/live/globalization/software-internationalization

**2. Internationalization for Windows Applications**
https://github.com/MicrosoftDocs/globalization/blob/live/windows/desktop/Intl/international-support

**3. National Language Support**
https://github.com/MicrosoftDocs/globalization/blob/live/windows/desktop/Intl/about-national-language-support

**Comment by jowilco** [comment]
After speaking with @alfredoalmeida, this appears to have been a temporary issue and both Alfredo and I can access all of the links in question.
