### ISSUE TITLE
National keyboard layouts page not working

### ISSUE THREAD

**Issue by PaulGor** [MicrosoftDocs/globalization#149]
https://docs.microsoft.com/en-us/globalization/windows-keyboard-layouts or the same at
https://github.com/MicrosoftDocs/globalization/blob/live/globalization/windows-keyboard-layouts.md

Does not work at all.
I tried Firefox with pop-up blocker disabled for microsoft.com and then tried MS Edge with pop-up blocker completely disabled and still nothing: click say on French or German or ... - nothing happens

**Comment by nschonni** [comment]
I think DocFx is sanitizing the `onclick` in general to open those links. Probably should just switch to regular links

**Comment by Paul-Dempsey** [comment]
That will create a poor experience if that's all that is done. Each of the keyboard implementations will need to be changed to provide a better layout in the context of an independent page, and also include a link back to windows-keyboard-layouts

**Comment by nschonni** [comment]
Alternately, since those layouts are small, they could be added into the table, but that might cause a whole other set of problems

**Comment by nschonni** [comment]
I think it allows `<iframe>` embeds, which could potentially keep the JS. Not saying it's a good idea, just throwing it out there

**Comment by jowilco** [comment]
@nschonni @PaulGor
We went with @nschonni 's suggestion and are using iframe embeds for now. We do need to take a longer look at how these keyboard snippets are generated, but for now the keyboards are usable again.

BTW, I apologize for not responding to this thread sooner - we had the keyboards "working" again in January, but the solution was pretty ugly.

**Comment by PaulGor** [comment]
Hi John

"are using iframe embeds for now" - how to use them? I tried MS Edge,
Chrome, Firefox and - same result, say I choose French and see only HTML
code for iframe:

---------------------------------
French Keyboard 

To see different keyboard states, move the mouse over state keys such as
Shift, Caps or AltGr. You can also lock or unlock those keys by clicking
them. 

<iframe src="kbdfr.html"></iframe> 

------------------------

-- Regards, Paul Gorodyansky 

On 2021-04-27 18:03, John Wilcock wrote:

> @nschonni [1] @PaulGor [2]
> We went with @nschonni [1] 's suggestion and are using iframe embeds for now. We do need to take a longer look at how these keyboard snippets are generated, but for now the keyboards are usable again. 
> 
> BTW, I apologize for not responding to this thread sooner - we had the keyboards "working" again in January, but the solution was pretty ugly. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe [4].
 

Links:
------
[1] https://github.com/nschonni
[2] https://github.com/PaulGor
[3]
https://github.com/MicrosoftDocs/globalization/issues/149#issuecomment-827966112
[4]

**Comment by jowilco** [comment]
Hi @PaulGor,

That's interesting... So far I have validated the behavior on Edge and Chrome both inside and outside of the Microsoft firewall and everything is displaying correctly. What should happen is first you should get a message that the keyboard is loading:
![image](https://user-images.githubusercontent.com/16766027/116328383-be46e580-a77d-11eb-8669-15f72fa25bf1.png)
then the keyboard is displayed:
![image](https://user-images.githubusercontent.com/16766027/116328406-cdc62e80-a77d-11eb-8d7b-755489072314.png)

I don't think that it is as simple as having Javascript disabled in your browser as that would have a much bigger effect.

If you open developer tools in your browser (F12 in Edge/Chrome), are there any messages in the console?

Thanks
John

**Comment by PaulGor** [comment]
Hi 

It's my fault - in the ticket there are TWO links and I somehow hit 2nd
one - and now I tried 1st one and all is OK:

https://docs.microsoft.com/en-us/globalization/windows-keyboard-layouts
or the same at
https://github.com/MicrosoftDocs/globalization/blob/live/globalization/windows-keyboard-layouts.md

-- Regards, Paul Gorodyansky 

On 2021-04-27 20:30, John Wilcock wrote:

> Hi @PaulGor [1], 
> 
> That's interesting... So far I have validated the behavior on Edge and Chrome both inside and outside of the Microsoft firewall and everything is displaying correctly. What should happen is first you should get a message that the keyboard is loading:
> [2]
> then the keyboard is displayed:
> [3] 
> 
> I don't think that it is as simple as having Javascript disabled in your browser as that would have a much bigger effect. 
> 
> If you open developer tools in your browser (F12 in Edge/Chrome), are there any messages in the console? 
> 
> Thanks
> John 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [4], or unsubscribe [5].
 

Links:
------
[1] https://github.com/PaulGor
[2]
https://user-images.githubusercontent.com/16766027/116328383-be46e580-a77d-11eb-8669-15f72fa25bf1.png
[3]
https://user-images.githubusercontent.com/16766027/116328406-cdc62e80-a77d-11eb-8d7b-755489072314.png
[4]
https://github.com/MicrosoftDocs/globalization/issues/149#issuecomment-828050682
[5]

**Comment by jowilco** [comment]
@PaulGor Thanks for confirming!
