### ISSUE TITLE
Strange translation of "Learn More" on Russian Language Portal page

### ISSUE THREAD

**Issue by ezadonsky** [MicrosoftDocs/globalization#150]
"Learn More" is translated into Russian as "Выучить больше" on https://www.microsoft.com/ru-ru/language/

This a direct translation and it sounds silly. It should be something like "Узнать больше" or "Подробнее".

**Comment by agustd** [comment]
Thanks for reporting this, @ezadonsky . The localized content on this pages is a community-based effort. You can submit a pull request to improve the current translation. You may want to use the Microsoft Terminology Search tool available here: https://www.microsoft.com/en-us/language/Search. One of the translations listed there is "Дополнительные сведения".

**Comment by agustd** [comment]
@ezadonsky, further on this, we have provided your feedback tot he team that owns the Language Portal. They will follow up from their end. I am closing this issue for this repository.
