### ISSUE TITLE
United Kingdom layouts should show ISO keyboard

### ISSUE THREAD

**Issue by hickford** [MicrosoftDocs/globalization#158]
In the United Kingdom we use ISO keyboards (see https://deskthority.net/wiki/ANSI_vs_ISO ). However  https://docs.microsoft.com/en-us/globalization/keyboards/kbduk.html
 and https://docs.microsoft.com/en-us/globalization/keyboards/kbdukx.html show American-style ANSI keyboards:

![image](https://user-images.githubusercontent.com/105314/104817693-16875680-5823-11eb-912a-e9c62b64d856.png)

The  keyboards in the diagrams should look more like https://upload.wikimedia.org/wikipedia/commons/d/da/KB_United_Kingdom.svg . Compare the Enter keys (multirow vs single row)

![](https://upload.wikimedia.org/wikipedia/commons/d/da/KB_United_Kingdom.svg)

 https://docs.microsoft.com/en-us/globalization/windows-keyboard-layouts#U

**Comment by jowilco** [comment]
Hello @hickford. We have updated the keyboard layout per request. I believe that the original versions shown have been like that way for a long time...
