### ISSUE TITLE
US keyboard layout shows spurious extra key that doesn't exist

### ISSUE THREAD

**Issue by hickford** [MicrosoftDocs/globalization#159]
The US keyboard layout shown at https://docs.microsoft.com/en-us/globalization/keyboards/kbdus_7.html (linked from https://docs.microsoft.com/en-us/globalization/windows-keyboard-layouts#U) shows two backspace keys. This is incorrect. The second backslash key between  Left Shift and Z is unexpected; it doesn't exist on US keyboards. 

![image](https://user-images.githubusercontent.com/105314/104817632-c14b4500-5822-11eb-9438-ff5879ae313d.png)

The correct backslash is between 
Backspace and Enter. https://upload.wikimedia.org/wikipedia/commons/5/51/KB_United_States-NoAltGr.svg

![](https://upload.wikimedia.org/wikipedia/commons/5/51/KB_United_States-NoAltGr.svg)

Essentially this is a weird impossible mix of ANSI and ISO https://deskthority.net/wiki/ANSI_vs_ISO

**Comment by agustd** [comment]
Thanks for raising this issue, @hickford . Microsoft intentionally adds the extra backlash key to be inclusive of the 105 keyboard layout. https://en.wikipedia.org/wiki/File:ISO_keyboard_(105)_QWERTY_UK.svg.
