### ISSUE TITLE
Document how Font fallback really works

### ISSUE THREAD

**Issue by Socolin** [MicrosoftDocs/globalization#203]
Hello,

On this documentation https://docs.microsoft.com/en-us/globalization/input/font-technology there is no mention on how to configure Font Fallback or how it works

After a lot of experiment I was able to discover that at least GDI+ is using a logical font https://docs.microsoft.com/en-us/windows/win32/intl/using-ms-shell-dlg-and-ms-shell-dlg-2 withi is then substitute with the font substitution mechanism and then Tahoma or Microsoft Sans Serif is used.

I don't know if this can be generalize, but it would have saved me a few hours of research if I had know those fonts were used in this process.

**Comment by jowilco** [comment]
@Socolin - Just acknowledging your comment. We are currently revamping all of the content in the site, and we'll look at adding information on how font fallback, depending on the technology used, works, .
In the meantime, if you have specific changes to add to the existing content, please feel free to submit a Pull request.

**Comment by Socolin** [comment]
I don't think I can open a PR since I'm not sure to what extent what I found by testing can be generalize to other system. I only try this on GDI+. And since there is already a note in the Font Linking that say GDI+ is not working the same way as other part (not supporting scaling factors) I prefer wait for this.

This comment show up in google already, so I think people looking for this information can find it..

**Comment by jowilco** [comment]
@Socolin - I apologize that it has taken so long, but the new version of the page at https://learn.microsoft.com/en-us/globalization/fonts-layout/fonts contains some information about font fallback. Unfortunately, because different systems/applications/etc. support different implementations of font fallback, we can't be too specific about how font fallback works universally, but I hope that the additional information might be helpful.

**Comment by Socolin** [comment]
Ok thanks.

I suppose some info I would like to have are too specific and are not documentable, but it's already much better to have a page that list everything about this topic :) It would have help me back then.

**Comment by moi15moi** [comment]
It would be nice if it could contains the information on how GDI find a fallback font when the font isn't in ``HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink``
