### ISSUE TITLE
Ligatures are missing on keyboard layout previews

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/globalization#222]
[Gothic keyboard layout](https://learn.microsoft.com/en-us/globalization/keyboards/kbdgthc) is missing some key character values:

<img width="726" alt="image" src="https://user-images.githubusercontent.com/1285934/208440214-466c8ecb-5769-45e5-9fb8-f583837bdba5.png">

Scan code `0x15` -> `VK_Y` -> `𐌹̈`:
```
𐌹̈ U+D800 U+DF39 U+0308
	U+D800 U+DF39 = U+10339 GOTHIC LETTER EIS
	U+0308 COMBINING DIAERESIS
```

Scan code `0x29` -> `VK_OEM_8` -> `̱̄`:
```
̱̄ U+0331 U+0304
	U+0331 COMBINING MACRON BELOW
	U+0304 COMBINING MACRON
```

See for proper preview: https://kbdlayout.info/kbdgthc

I guess [other layouts](https://kbdlayout.info/features/ligatures) are affected too.

**Comment by DJm00n** [comment]
Another example is Buginese keyboard
<img width="749" alt="image" src="https://user-images.githubusercontent.com/1285934/208084605-6f33f190-4580-4903-920b-3ca75d8e84f5.png">

Scan code 0x1e -> VK_A:
```
ᨕ U+1A15 BUGINESE LETTER A
SHIFT: ᨕᨗ‍ᨐ U+1A15 U+1A17 U+200D U+1A10
	U+1A15 BUGINESE LETTER A
	U+1A17 BUGINESE VOWEL SIGN I
	U+200D ZERO WIDTH JOINER
	U+1A10 BUGINESE LETTER YA
```

https://kbdlayout.info/kbdbug

**Comment by jowilco** [comment]
@DJm00n - Thank you for identifying these issues. I will try to fix them within the next two weeks.

**Comment by jowilco** [comment]
@DJm00n - I had some time today to look at the code that generates the keyboards. We are currently not handling the ligatures, although the ligature information is available. In theory, we should be able to generate keys showing the ligatures, it would require a significant rewrite of the code. We will need to prioritize this work, and I will comment on this thread within the next two weeks.

**Comment by jowilco** [comment]
@DJm00n - Thank you again for catching this issue. I was able to update the generator to support the ligatures and the keyboards have been updated. Please let me know if the updated keyboards meet your expectations. Please also feel free to close this issue if you feel that everything is now resolved.

Note that there are slight differences in how some of the fonts are displayed. This has to do with how the images for the ligatures are generated when compared to how the other keyboard images are generated. In the future, we can look at generating all images using the new process for ligatures, but perhaps not a high priority task at this time.

**Comment by DJm00n** [comment]
Thank you @jowilco! Looks good now. One thing that is missing right now - ‘U+00000’ codes on the button popup for ligatures. Can you add that too?

**Comment by DJm00n** [comment]
Thank you @jowilco! Now at least we can see real Unicode codes that will be generated on a key press. It is indeed more logical if you’re limited by what MSKLC doing.  Closing this bug. 

Can I expect those fixes will be done in MSKLC in some future or it is a “dead” project?

**Comment by jowilco** [comment]
@DJm00n It wasn't too difficult to address, so I've added alternative descriptions for ligatures where a surrogate pair is used. Note that at this time it only affects the Gothic keyboard's Gothic Letter Eis +Combining Diaeresis. I hope that this is helpful.

**Comment by DJm00n** [comment]
Nice! Thank you!
