### ISSUE TITLE
Navigation is broken on keyboard preview pages

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/globalization#241]
I cannot properly navigate after I open some keyboard layout preview page:

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/1285934/218303432-6057ac0b-bcf9-45b7-a5a7-d83fc236f5fc.png">

Keyboard layout preview pages should be [under this page](https://learn.microsoft.com/en-us/globalization/windows-keyboard-layouts) in hierarchy:
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/1285934/218303558-3559ba1d-2b0d-4d5b-a1ca-d380aea3730a.png">

Also, please add a link to [Keyboard identifiers and input method editors for Windows](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values) somewhere on [Windows keyboard layouts](https://learn.microsoft.com/en-us/globalization/windows-keyboard-layouts) page.

**Comment by jowilco** [comment]
@DJm00n - Fixed with PR #242. If you agree, please close.

**Comment by DJm00n** [comment]
@jowilco not it is better but I still think layout pages should be under [Windows keyboard layouts](https://learn.microsoft.com/en-us/globalization/windows-keyboard-layouts) page.

![image](https://user-images.githubusercontent.com/1285934/218679681-73223228-06fa-4eeb-9325-158822301ee3.png)

**Comment by jowilco** [comment]
@DJm00n I added a rule specifically for the keyboards. Microsoft's new style is not to use the TOC structure for breadcrumbs, but as the keyboards aren't even in the TOC, I agree that the user experience would be better in this case.

**Comment by DJm00n** [comment]
Nice. Thank you @jowilco!
