### ISSUE TITLE
Direct keyboard layout pages shouldn't be accessed

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/globalization#257]
When I googling for "Albanian Keyboard layout windows" I seeing direct link to the keyboard layout page (https://learn.microsoft.com/en-us/globalization/keyboards/kbdal.html)

![image](https://github.com/MicrosoftDocs/globalization/assets/1285934/0d413171-eeb6-4665-9e02-fc1e150dd2ab)

but page with proper navigation (https://learn.microsoft.com/en-us/globalization/keyboards/kbdal) should  should be opened instead.

![image](https://github.com/MicrosoftDocs/globalization/assets/1285934/0d4f9385-f44d-4278-a113-848a9225dbe7)

Please make some changes to prevent this from happening.

**Comment by DJm00n** [comment]
@jowilco

**Comment by jowilco** [comment]
@DJm00n I've added robots/noindex for the individual keyboard HTML files (but not the topics that contain the HTML files). This should work for search engines that respect robots/noindex. It might take a little while to propagate to the search engines.
