### ISSUE TITLE
Include keyboard identified on keyboard layout pages

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/globalization#258]
This page now has a list of keyboard identifiers (KLID string) for each keyboard layout supplied with Windows, and a link to the corresponding layout:
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values

Please include this identifier on corresponding keyboard layout pages. This way it will be easier to deal with keyboard layouts.

PS: Yes, there is much more information about layouts at https://kbdlayout.info/, but I wanted to improve the official source.

**Comment by jowilco** [comment]
@DJm00n - Thanks for the 3 issues. I'll try to address them within the next couple of weeks.

**Comment by jowilco** [comment]
Added to https://learn.microsoft.com/en-us/globalization/windows-keyboard-layouts.

Please close if you feel this is sufficient.

**Comment by DJm00n** [comment]
Thank you @jowilco!
Can you please also add these identifiers on each of **individual** keyboard layout pages?

**Comment by jowilco** [comment]
@DJm00n: Good suggestion! Done.

**Comment by DJm00n** [comment]
Thank you @jowilco!
