### ISSUE TITLE
Most links are pointing to the old MSDN site rather than new pages on this site

### ISSUE THREAD

**Issue by brunolewin-msft** [MicrosoftDocs/globalization#36]
Most links are pointing to the old MSDN site rather than new pages on this site. 
See example below for 
https://github.com/MicrosoftDocs/globalization/blob/master/globalization/software-internationalization.md

---
title: Software Internationalization
description: Fundamentals about software internationalization, which includes globalization, localizability, localization, and testing world readiness.
ms.assetid: 9c23e01d-81c8-4e00-8b1f-068bb63713c4
ms.date: 07/14/2017
---

# Software Internationalization

## Introduction

With the growing software market far beyond the English-speaking world, it's important for the software to support various text and data formats to reach all the potential customers. To make that happen, the most important step is to design the software with the internationalization in mind.

The below sections provide some generic information about the internationalization concepts—globalization, localizability, and localization.

## Data Encoding

[Encoding Overview](https://msdn.microsoft.com/en-US/library/mt683841)

[Transformation of Unicode Code Points](https://msdn.microsoft.com/en-US/library/mt683843)

[Byte Order Mark](https://msdn.microsoft.com/en-US/library/mt683845)

[Surrogate Pairs](https://msdn.microsoft.com/en-US/library/mt683846)

[Code Pages](https://msdn.microsoft.com/en-US/library/mt662301)

## Locale and Culture Awareness

[Using Locale Model](https://msdn.microsoft.com/en-US/library/mt662310)

[Sorting and String Comparison](https://msdn.microsoft.com/en-US/library/mt662313)

[Calendar Differences](https://msdn.microsoft.com/en-US/library/mt662317)

[Date Formatting](https://msdn.microsoft.com/en-US/library/mt662320)

[Time Formatting](https://msdn.microsoft.com/en-US/library/mt662321)

[Number Formatting](https://msdn.microsoft.com/en-US/library/mt662324)

[Addresses](https://msdn.microsoft.com/en-US/library/mt662325)

[Telephone Number](https://msdn.microsoft.com/en-US/library/mt662326)

[Paper Size](https://msdn.microsoft.com/en-US/library/mt662327)

[Units of Measurement](https://msdn.microsoft.com/en-US/library/mt662328)

## Input, Output, and Display

[Text Input, Output, and Display](https://msdn.microsoft.com/en-US/library/mt662329)

[Capitalization, Uppercasing, and Lowercasing](https://msdn.microsoft.com/en-US/library/mt662330)

[Fonts](https://msdn.microsoft.com/en-US/library/mt662331)

[Line and Word Breaking](https://msdn.microsoft.com/en-US/library/mt662334)

[Complex Scripts Awareness](https://msdn.microsoft.com/en-US/library/mt662335)

[Console Globalization](https://msdn.microsoft.com/en-US/library/mt662336)

## Localizability

[Localizability Overview](https://msdn.microsoft.com/en-US/library/mt651700)

[Isolate Localizable Resources](https://msdn.microsoft.com/en-US/library/mt662338)

[String Handling](https://msdn.microsoft.com/en-US/library/mt662339) 

[Mirroring Awareness](https://msdn.microsoft.com/en-US/library/mt662340)

[UI Considerations](https://msdn.microsoft.com/en-US/library/mt662341)

## Localization

[Localization Overview](https://msdn.microsoft.com/en-US/library/mt662355)

[Localization Elements](https://msdn.microsoft.com/en-US/library/mt662343)

[Localization Tools](https://msdn.microsoft.com/en-US/library/mt662351)

[Localization Team](https://msdn.microsoft.com/en-US/library/mt662352)

[Establishing Localization Guidelines](https://msdn.microsoft.com/en-US/library/mt662353)

[Content Localization](https://msdn.microsoft.com/en-US/library/mt662354)

## Testing for World Readiness

[Quality Assurance for World-Readiness](https://msdn.microsoft.com/en-US/library/mt662412)

[The World-Ready Approach to Testing](https://msdn.microsoft.com/en-US/library/mt662413)

[Globalization of the Test](https://msdn.microsoft.com/en-US/library/mt662415)

[Localizability Testing](https://msdn.microsoft.com/en-US/library/mt651780)

[Localization Testing](https://msdn.microsoft.com/en-US/library/mt662422)

[The Role of Test Tools](https://msdn.microsoft.com/en-US/library/mt662423)

[Sample International Test Cases](https://msdn.microsoft.com/en-US/library/mt662424)

**Comment by GwynethM** [comment]
Should now be resolved on this and other pages. Thanks for pointing this out.
