### ISSUE TITLE
This docset has no PR Preview

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/globalization#51]
I can't preview PRs on review.docs.microsoft.com

(Edited since now I can see the edit button)

**Comment by mairaw** [comment]
And also no PR Preview

**Comment by mairaw** [comment]
@Paul-Dempsey I think this might have been fixed already from what I can see in the config. Do you want me to open a test PR?

**Comment by mairaw** [comment]
I think I fixed that later on with PR #62

**Comment by Paul-Dempsey** [comment]
@mairaw - thanks!
